micronaut:
  application:
    name: valstats
  server:
    port: 8080
    response-compression:
      enabled: true
      mime-types: application/json
  http:
    client:
      read-timeout: 30s
      url-encoding: standard

netty:
  default:
    allocator:
      max-order: 3
