micronaut:
  application:
    name: valstats-api-lambda
  http:
    client:
      read-timeout: 30s
      url-encoding: standard

aws:
  region: us-east-1

dynamodb:
  table-name: valstats

valorant:
  api-key: ${HDEV_KEY:}

