micronaut:
  application:
    name: valstats-api-lambda
  http:
    client:
      read-timeout: 30s
      url-encoding: standard

aws:
  region: us-east-1

dynamodb:
  table-name: ${DYNAMODB_TABLE_NAME:valstats}

refresh:
  queue-url: ${REFRESH_QUEUE_URL:}

valorant:
  api-key: ${HDEV_KEY:}

henrik-api:
  secret-arn: ${HENRIK_API_SECRET_ARN:}
